Storyshot Fixes
webex/components pull request #131
Opened 2020-09-25 00:23 UTC by lalli-flores

* IDs in Momentum UI buttons keep changing whenever a story was moved, as they are sequentially assigned, mocking the IDs so they are fixed
* Fixing Storybook so it finds Avatar images when it's hosted
* Fixed (🤞🏼) old Storybook builds not being removed from Git

2020-09-25 16:30 UTC, adamweeks commented on .circleci/config.yml
> +            git commit -m "docs: build Storybook"
Committing this to the master branch will trigger another build. We'll need to add `[skip ci]`.

```suggestion
            git commit -m "docs: build Storybook [skip ci]"
```

2020-09-25 16:32 UTC, adamweeks commented on src/storyshots.test.js
> +jest.mock('react-uid', () => ({
Awesome find!

2020-09-25 16:33 UTC, adamweeks requested changes
Need to update the circle config with skip ci.

2020-09-25 17:25 UTC, lalli-flores commented on src/storyshots.test.js
> +jest.mock('react-uid', () => ({
Took me all afternoon! But worth it

2020-09-25 17:26 UTC, lalli-flores commented
I was laying it bed last night wondering if I added the skip CI or not, I guess I didn't 😂

2020-09-25 18:12 UTC, adamweeks approved these changes
LGTM!

2020-09-25 18:29 UTC, merged

2020-11-18 23:40 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.45.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/components/v/1.45.4)
- [GitHub release](https://github.com/webex/components/releases/tag/v1.45.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: