build(bump): allowing newest momentum ui for node bump
webex/components pull request #154
Opened 2021-01-19 20:14 UTC by peter7cole

Missing the caret on the momentum-ui/react dependency, which is breaking a bump in Cisco Online Account Management Portal. Thank you!

2021-01-19 20:22 UTC, lalli-flores requested changes
Momentum UI is a peer dependency of the components, so we should not include it as part of the dependencies.

2021-01-19 21:31 UTC, taymoork2 commented
@peter7cole you can squash everything into one commit and rebase to solve the package-lock conflict

2021-01-19 22:12 UTC, lalli-flores approved these changes

2021-01-19 22:12 UTC, merged

2021-01-21 21:39 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.45.6 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/components/v/1.45.6)
- [GitHub release](https://github.com/webex/components/releases/tag/v1.45.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: