feat(WebexJsonAdaptor): add demonstration video for remote sharing
webex/components pull request #208
Opened 2021-04-20 12:44 UTC by alinasuciu

Add a new video in story in order to visually demonstrate the remote share in action 

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227222

2021-04-20 15:04 UTC, cipak approved these changes

2021-04-21 01:26 UTC, lalli-flores requested changes
Changes look good. Please use the attach video for screen share.

https://user-images.githubusercontent.com/6610308/115483511-c646d880-a205-11eb-95e4-56d629812ecf.mp4

2021-04-21 11:30 UTC, alinasuciu commented
> Changes look good. Please use the attach video for screen share.
> 
>  ongoing-share.mp4

done

2021-04-21 23:03 UTC, lalli-flores approved these changes

2021-04-21 23:08 UTC, merged

2021-04-21 23:11 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.60.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/components/v/1.60.0)
- [GitHub release](https://github.com/webex/components/releases/tag/v1.60.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: