build(workflow): trigger event on new version
webex/components pull request #221
Opened 2021-04-28 11:08 UTC by maloun96

2021-05-11 21:31 UTC, cipak commented on .github/workflows/dispatch-new-version-event.yml
> +        # TODO: change urls for repositories
@lalli-flores if you can approve despite the urls not being updated, we'll update the urls tomorrow and merge

2021-05-11 21:33 UTC, cipak commented on .github/workflows/dispatch-new-version-event.yml
> +      - name: Dispatch initiating repository event
> Dispatch new version event

2021-05-12 06:14 UTC, lalli-flores requested changes
This workflow needs to look a lot more like the one in the [interfaces repo](https://github.com/webex/component-adapter-interfaces/blob/master/.github/workflows/dispatch-new-version-event.yml). Not only the URLs need to be updated (I know you're aware) but we also need to make sure that 
* This only triggers on push to `master` and not on dispatch
* This only calls the dispatch API if there's actually a version change

Please also update your description to something similar like the [PR in the interfaces repo](https://github.com/webex/component-adapter-interfaces/pull/53)

2021-05-12 06:29 UTC, lalli-flores commented on .github/workflows/dispatch-new-version-event.yml
> +          -u ${{ secrets.PERSONAL_TOKEN }} \
```suggestion
          -u ${{ secrets.ACCESS_TOKEN }} \
```

2021-05-13 02:10 UTC, lalli-flores approved these changes

2021-05-13 02:17 UTC, merged

2021-05-17 04:41 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.63.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/components/v/1.63.1)
- [GitHub release](https://github.com/webex/components/releases/tag/v1.63.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: