fix(WebexAvatar): update avatar badge background color and font size
webex/components pull request #450
Opened 2021-09-21 07:03 UTC by BenjaminGolya

2021-09-22 06:01 UTC, lalli-flores requested changes
Padding around the badge doesn't look right
![image](https://user-images.githubusercontent.com/6610308/134290961-f6a218de-cf76-4734-a166-5cbe14c838b2.png)

2021-09-22 09:42 UTC, BenjaminGolya commented
> Padding around the badge doesn't look right
> ![image](https://user-images.githubusercontent.com/6610308/134290961-f6a218de-cf76-4734-a166-5cbe14c838b2.png)
> 
> vs spec
> <img alt="Bot Badge Updated" width="277" src="https://user-images.githubusercontent.com/6610308/134291031-5f0923d4-0d59-4411-a4c9-3a38de0747ed.png">

Updated

2021-09-23 04:52 UTC, lalli-flores approved these changes

2021-09-23 04:52 UTC, merged

2021-09-23 04:57 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.142.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/components/v/1.142.3)
- [GitHub release](https://github.com/webex/components/releases/tag/v1.142.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: