Discrepancies
webex/components pull request #454
Opened 2021-09-21 12:13 UTC by lungancatalin

2021-09-22 08:52 UTC, alinasuciu commented
Please change commit message and add a more detailed description.

2021-09-22 09:00 UTC, alinasuciu approved these changes

2021-09-23 04:47 UTC, lalli-flores requested changes
Code looks good, but can you update your message to something meaningful for a third-party or the changelog?
maybe something like:
```
fix(WebexMemberRoster): style scroll bar and external user message

2021-09-27 10:57 UTC, CernaianuMihai approved these changes

2021-09-27 10:58 UTC, CernaianuMihai approved these changes

2021-09-29 07:17 UTC, lalli-flores approved these changes

2021-09-29 07:17 UTC, merged

2021-09-29 07:23 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.143.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/components/v/1.143.4)
- [GitHub release](https://github.com/webex/components/releases/tag/v1.143.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: