feat(WebexComponents): add pressed state on "Participant", "Share" and "Collapse" buttons
webex/components pull request #458
Opened 2021-09-21 18:19 UTC by patricia0817

Add active state on "Participant", "Share" and "Collapse" buttons
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-267952

2021-09-22 08:29 UTC, alinasuciu approved these changes

2021-09-22 08:29 UTC, alinasuciu commented on src/adapters/MeetingsJSONAdapter/controls/RosterControl.js
>      };
Please try to add an extra class if button has different style in order to simplify the logic.

2021-09-23 04:33 UTC, lalli-flores requested changes

2021-09-23 04:33 UTC, lalli-flores commented on src/components/WebexMeetingControl/WebexMeetingControl.jsx
> +import {ROSTER_CONTROL, SHARE_CONTROL} from '../../adapters/MeetingsJSONAdapter';
You should not import from adapters into the component code. How would work for other adapters? e.g. SDK adapter?

2021-09-23 04:33 UTC, lalli-flores commented on src/components/WebexMeetingControl/WebexMeetingControl.jsx
> +  const isPressed = (ID === ROSTER_CONTROL || ID === SHARE_CONTROL) && isActive;
Why are you hard coding specifically for this buttons? how would this work if we add another button that should behave this way? This is not scalable

2021-09-24 11:25 UTC, alinasuciu commented on src/components/WebexMeetingControl/WebexMeetingControl.jsx
>          type={controlTypeToButtonType[type] || 'default'}
I think it's enough to check if is active and add the class active although all the buttons will take this class if they are active and in css just add style for active class on pressable buttons.

2021-09-24 11:25 UTC, alinasuciu commented on src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
>        disabled={false}
correct this white space

2021-10-27 14:11 UTC, closed without merging