feat(signin): emit operational metrics
webex/components pull request #788
Opened 2022-05-26 06:06 UTC by sumit12690

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-311577

Emit Operational Metrics from Sign In components

2022-05-26 13:08 UTC, amritesi approved these changes

2022-05-26 13:29 UTC, harsh789rai requested changes
Please change the commit message from feat(signin) to feat(SignIn)

2022-05-27 04:50 UTC, harsh789rai approved these changes

2022-05-30 17:38 UTC, merged

2022-07-28 17:09 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.269.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/components/v/1.269.0)
- [GitHub release](https://github.com/webex/components/releases/tag/v1.269.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: